version: 2.1

jobs:
  build-docs:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install .[docs]

      - run:
          name: Build Sphinx docs
          no_output_timeout: 20m
          command: |
            cd doc;
            make html;

      # Save the outputs
      - store_artifacts:
          path: doc/_build/html/
          destination: dev
      - persist_to_workspace:
          root: doc/_build
          paths:
            - html


workflows:
  version: 2

  default:
    jobs:
      - build_docs:
          filters:  # required as `deploy` needs tag AND requires `build_docs`
            tags:
              only: /.*/
