.. role:: raw-html(raw)
   :format: html

.. role:: raw-latex(raw)
   :format: latex

.. |Feature| replace:: :raw-html:`<span class="badge text-bg-success">Feature</span>` :raw-latex:`{\small\sc [Feature]}`
.. |Efficiency| replace:: :raw-html:`<span class="badge text-bg-info">Efficiency</span>` :raw-latex:`{\small\sc [Efficiency]}`
.. |Enhancement| replace:: :raw-html:`<span class="badge text-bg-info">Enhancement</span>` :raw-latex:`{\small\sc [Enhancement]}`
.. |Fix| replace:: :raw-html:`<span class="badge text-bg-danger">Fix</span>` :raw-latex:`{\small\sc [Fix]}`
.. |API| replace:: :raw-html:`<span class="badge text-bg-warning">API Change</span>` :raw-latex:`{\small\sc [API Change]}`

.. rubric:: Legend for changelogs

- |Feature| something that you couldn't do before.
- |Efficiency| an existing feature now may not require as much computation or
  memory.
- |Enhancement| a miscellaneous minor improvement.
- |Fix| something that previously didn't work as documented -- or according
  to reasonable expectations -- should now work.
- |API| you will need to change your code to have the same effect in the
  future; or a feature will be removed in the future.